repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.4
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]
      - id: ruff-format
  - repo: https://github.com/CJHwong/pre-commit-import-linter
    rev: 2.1.0
    hooks:
      - id: pre-commit-import-linter
